# -*- coding: utf-8 -*-
"""paiproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJ03OGI4fIGdRE16d1gXaT-icmFuojyW
"""

#Import libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

# Load data
df_train = pd.read_csv('/content/sample_data/Titanic_train.csv')
df_test = pd.read_csv('/content/sample_data/Titanic_test.csv')
print(df_train.head())
print("for test\n")
print(df_test.head())

print(df_train.isnull())
print(df_test.isnull())
# Imputation for numerical columns
df_train.fillna(df_train.mean(numeric_only=True), inplace=True)
df_test.fillna(df_test.mean(numeric_only=True), inplace=True)

# Imputation for categorical columns
# Fill 'Cabin' with 'Unknown' in both train and test sets
df_train['Cabin'] = df_train['Cabin'].fillna('Unknown')
df_test['Cabin'] = df_test['Cabin'].fillna('Unknown')

# Fill 'Embarked' with its mode in the train set
# Assuming 'Embarked' is not missing in test or that it was handled by previous fillna if numeric.
# Check if 'Embarked' has nulls in df_train before filling
if df_train['Embarked'].isnull().any():
    df_train['Embarked'] = df_train['Embarked'].fillna(df_train['Embarked'].mode()[0])

# Re-check for nulls after imputation
print("\nNulls after imputation for df_train:")
print(df_train.isnull().sum())
print("\nNulls after imputation for df_test:")
print(df_test.isnull().sum())

print("Number of duplicate rows in df_train:", df_train.duplicated().sum())
print("Number of duplicate rows in df_test:", df_test.duplicated().sum())

# Split data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.model_selection import GridSearchCV

# Define the parameter grid to search
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs'] # 'liblinear' works well for small datasets and L1/L2 regularization
                                      # 'lbfgs' is a good default for larger datasets
}

# Instantiate Logistic Regression model
logreg = LogisticRegression(max_iter=2000, random_state=42) # Use max_iter from previous cells

# Instantiate GridSearchCV
grid_search = GridSearchCV(logreg, param_grid, cv=5, scoring='accuracy', n_jobs=-1) # cv=5 for 5-fold cross-validation

# Fit GridSearchCV to the scaled training data
grid_search.fit(X_train_scaled, y_train)

# Print the best parameters and best score
print("Best parameters: ", grid_search.best_params_)
print("Best cross-validation accuracy: ", grid_search.best_score_)

# Get the best model
best_logreg_model = grid_search.best_estimator_

# Evaluate the best model on the validation set
y_pred_tuned = best_logreg_model.predict(X_val_scaled)
accuracy_tuned = accuracy_score(y_val, y_pred_tuned)

print("Validation Accuracy with Best Model: ", accuracy_tuned)

from sklearn.model_selection import GridSearchCV

# Define the parameter grid to search
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs'] # 'liblinear' works well for small datasets and L1/L2 regularization
                                      # 'lbfgs' is a good default for larger datasets
}

# Instantiate Logistic Regression model
logreg = LogisticRegression(max_iter=2000, random_state=42) # Use max_iter from previous cells

# Instantiate GridSearchCV
grid_search = GridSearchCV(logreg, param_grid, cv=5, scoring='accuracy', n_jobs=-1) # cv=5 for 5-fold cross-validation

# Fit GridSearchCV to the scaled training data
grid_search.fit(X_train_scaled, y_train)

# Print the best parameters and best score
print("Best parameters: ", grid_search.best_params_)
print("Best cross-validation accuracy: ", grid_search.best_score_)

# Get the best model
best_logreg_model = grid_search.best_estimator_

# Evaluate the best model on the validation set
y_pred_tuned = best_logreg_model.predict(X_val_scaled)
accuracy_tuned = accuracy_score(y_val, y_pred_tuned)

print("Validation Accuracy with Best Model: ", accuracy_tuned)

print(X_train.dtypes)

"""The `GridSearchCV` process identifies the optimal hyperparameters for the Logistic Regression model and provides a more robust accuracy estimate through cross-validation. The final validation accuracy using the best model is also printed, allowing for a comparison with the previous model's accuracy."""